; /etc/supervisor/conf.d/nebulo-worker.conf
[program:nebulo-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/nebulo/current/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=1800
user=nebulo
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=1810
redirect_stderr=true
stdout_logfile=/var/www/nebulo/shared/storage/logs/worker.log
